server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    # root directory where the static files will be placed
    root   /usr/share/nginx/html;
    index  taskpane.html index.html index.htm;

    # Always serve the requested file, fallback to taskpane.html if not found (React Router support)
    location / {
        try_files $uri $uri/ /taskpane.html;
    }

    # Add caching headers for static assets
    location ~* \.(?:css|js|jpg|svg|ico|png|xml)$ {
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
    }

    # Error pages
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
